### PR TITLE
Add clean target deleting poetry env

### PR DESCRIPTION
**Pull request by mdujava**

### CODE REVIEW

**Review by averevki — COMMENTED** [review]
Clean target and some others were removed during the migration(https://github.com/Kuadrant/testsuite/pull/147) to leave the user to manage his own environments. Is this needed now? Thoughts @pehala?

**Comment by pehala** [comment]
Not sure about this. Would it be possible for us to create and/or delete a specific env that we know was created by the makefile? Meaning delete would only delete the correct env and not mess up users own envs.

**Comment by mdujava** [comment]
I think yes, if  `make poetry[-dev]` would install the env and save the name into the `.make-poetry-sync` then clean could only delete that env. WDYT?

**Comment by mganisin** [comment]
And what if make created and used one specific env name? (unless env= said otherwise)

**Comment by pehala** [comment]
Closing this, as Poetry env management in Makefile deserves a rework as whole

**Pull request closed without merging**
