### PR TITLE
Fix metrics tests broken by reformat

### PR DESCRIPTION
**Pull request by averevki**
Were broken by #235 and #228

### CODE REVIEW

**Review by jsmolar — APPROVED** [review]
The only thing that I am scared of, is over-extending `OpenShiftClient`.

**Review by azgabur — APPROVED** [review]

**Comment by pehala** [comment]
> The only thing that I am scared of, is over-extending `OpenShiftClient`.

Agreed, I am fine with this particular method, but the alternative might be to move it to be a class method in OpenShiftRoute. @jsmolar WDYT?

**Comment by jsmolar** [comment]
> > The only thing that I am scared of, is over-extending `OpenShiftClient`.
> 
> Agreed, I am fine with this particular method, but the alternative might be to move it to be a class method in OpenShiftRoute. @jsmolar WDYT?

I don't like `OpenShiftRoute` either. The best place would be to get it straight from the service, but it is pointless to create such an object just for this. I am afraid I don't have an answer for this.

**Comment by pehala** [comment]
Merging for now, we might resolve this when we add a Service object.

**Pull request merged**
