### PR TITLE
Bump python to 3.11 in acceptance.yml

### PR DESCRIPTION
**Pull request by azgabur**
To fix failing test in #212

### CODE REVIEW

**Comment by pehala** [comment]
IF you want to bump the minimum required python version to 3.10 you would need to bump it in more places like README or Dockerfile

**Comment by azgabur** [comment]
I updated README and Dockerfile. Bumping one more version to 3.11 as previous version was not available in centos9 repositories.

**Review by pehala — DISMISSED** [review]

**Comment by averevki** [comment]
You probably should also change it in `pyproject.toml`. 3.11 is Python's lastest version and still some packages may not support it. Although there aren't many now, I think you should still check for testsuite packages compatibility. I found at least one package, `backoff`, that is not supporting Python 3.11 explicitly and is frequently used in tests (https://pypi.org/project/backoff/). I also found a Python 3.11 compatibility table with most popular packages https://pyreadiness.org/3.11/

**Comment by pehala** [comment]
> You probably should also change it in `pyproject.toml`. 3.11 is Python's lastest version and still some packages may not support it. Although there aren't many now, I think you should still check for testsuite packages compatibility. I found at least one package, `backoff`, that is not supporting Python 3.11 explicitly and is frequently used in tests (https://pypi.org/project/backoff/). I also found a Python 3.11 compatibility table with most popular packages https://pyreadiness.org/3.11/

Does not support or does not work?

**Comment by averevki** [comment]
> > You probably should also change it in `pyproject.toml`. 3.11 is Python's lastest version and still some packages may not support it. Although there aren't many now, I think you should still check for testsuite packages compatibility. I found at least one package, `backoff`, that is not supporting Python 3.11 explicitly and is frequently used in tests (https://pypi.org/project/backoff/). I also found a Python 3.11 compatibility table with most popular packages https://pyreadiness.org/3.11/
> 
> Does not support or does not work?

3.11 is not listed on pypi package page. So I think it should at least be tested.

**Comment by pehala** [comment]
I have been using 3.11 for some time, so I do not expect any problems, feel free to run the entire testsuite on it though

**Comment by azgabur** [comment]
Updated `pyproject.toml` and run `make test` and everything passed with occasional fails that after re-run pass.

**Review by pehala — APPROVED** [review]

**Review by jsmolar — APPROVED** [review]

**Pull request merged**
