### PR TITLE
Add DNSPolicy health check tests

### PR DESCRIPTION
**Pull request by averevki**
Test cases:
- Healthy endpoint with TLS
- Healthy endpoint without TLS
- Unhealthy endpoint
- Endpoint removal and return

Also added classes for the health check section of the DNSPolicy and for the DNSHealthCheckProbe CR

Part of the #572

### CODE REVIEW

**Comment by trepel** [comment]
It looks good to me and it (more or less) worked yesterday for me, but today with a new Kuadrant nightly build it does not work. The reason is that DNSPolicy keeps being successfully enforced despite failing health_check. So this piece:
```
    assert dns_policy.wait_until(has_condition("Enforced", "False"))
    assert dns_policy.wait_until(
        has_record_condition("Ready", "False", "HealthChecksFailed", "None of the healthchecks succeeded")
    )
```
is never true. Not sure if there has been any changes related to this behavior recently and whether it is intended or not but it seems like a bug to me.

**Comment by trepel** [comment]
It happened to me twice that I got following error:
```
testsuite/kuadrant/policy/dns.py:99: in get_dns_health_probe
    dns_probe = self.get_owned("dnsrecords.kuadrant.io")[0].get_owned("DNSHealthCheckProbe")[0]
E   IndexError: list index out of range
```
As if the resource has not been created yet or ownership relationship has not been established quickly enough. I don't think this is something to fix in this PR - we'll see in nightlies whether this is worth investigating or not.

**Review by jsmolar — DISMISSED** [review]

**Comment by averevki** [comment]
> It looks good to me and it (more or less) worked yesterday for me, but today with a new Kuadrant nightly build it does not work. The reason is that DNSPolicy keeps being successfully enforced despite failing health_check. So this piece:
> 
> ```
>     assert dns_policy.wait_until(has_condition("Enforced", "False"))
>     assert dns_policy.wait_until(
>         has_record_condition("Ready", "False", "HealthChecksFailed", "None of the healthchecks succeeded")
>     )
> ```
> 
> is never true. Not sure if there has been any changes related to this behavior recently and whether it is intended or not but it seems like a bug to me.

Thanks, there were indeed some changes in the dnspolicy. Adjusted now :+1:

**Review by trepel — APPROVED** [review]
Code looks good to me. Tests passed against November 19 nightly build. Approving this one.

**Pull request merged**
