### PR TITLE
Update default settings

### PR DESCRIPTION
**Pull request by averevki**
Update default settings due to the introduced change in https://github.com/Kuadrant/testsuite/pull/516

### CODE REVIEW

**Review by azgabur — APPROVED** [review]

**Review by trepel — APPROVED** [review]
LGTM, but why not to add `cluster2: {}` as well?

**Review by azgabur — CHANGES_REQUESTED** [review]
Please add reasonable defaults for `dns` category as well

**Comment by averevki** [comment]
> Please add reasonable defaults for `dns` category as well

Only defaults I can set for DNS settings are public DNS servers, which would fail on the RH network we all use most of the time. There is an example with public servers in .tpl settings. I don't think we can set anything general for this test, let me know if you have something in mind

**Review by azgabur — APPROVED** [review]

**Comment by azgabur** [comment]
If geo tests will be skipped, then no default `dns` is needed
https://github.com/Kuadrant/testsuite/pull/537

**Pull request merged**
