### PR TITLE
Move has_condition to policy module

### PR DESCRIPTION
**Pull request by pehala**
There is still dependence on `check_condition` from utils. That method is used in route and gateway and moving it here might cause dependency cycle

### CODE REVIEW

**Comment by averevki** [comment]
Couldn't has_condition be used for something other than policies in the future?

**Comment by pehala** [comment]
> Couldn't has_condition be used for something other than policies in the future?

Theoretically yes

**Review by trepel — APPROVED** [review]
Validated via `make testsuite/tests/./kuadrant/gateway/reconciliation/test_gw_doesnt_exist.py` LGTM

**Review by jsmolar — APPROVED** [review]
Such methods (potentially used by any Kubernetes object) should have be in one common file.

**Pull request merged**
